### ISSUE TITLE
Add an event landing page for the show

### ISSUE THREAD

**Issue by ArsalaBangash** [UTM-Hacklab/utmhacklab.tech#6]
### Notes

This requires a custom layout under .components. [Learn more](https://medium.com/vue-mastery/how-to-create-a-custom-vuepress-theme-with-vuetify-651b7d7e5092)

**Comment by George-lewis** [comment]
I've created a proof of concept landing-page for the event. Please find it at `/showcase` on the showcase-landing branch. The README.md uses a custom styleclass which is customized in `.vuepress/styles/index.styl`. I still need to look into per-page stylesheets and possibly having raw html rather than markdown files.
